---
global:
  scrape_native_histograms: true

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/dolved-observability/rules/*.yaml

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - deployment.environment.name
    - container.name

storage:
  tsdb:
    out_of_order_time_window: 10m
