/* eslint-disable jsx-a11y/label-has-associated-control -- Radix Select trigger is nested in its visible label. */
"use client";

import { FileSearch, RefreshCw, Trash2 } from "lucide-react";
import { type FormEvent, useCallback, useState } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Notice } from "@/components/ui/notice";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StatusBadge, type StatusTone } from "@/components/ui/status-badge";
import { type AdminDocument, type DocumentPage, deleteWorkspaceDocument, firstError, retryWorkspaceDocument, workspaceDocuments } from "@/lib/api";
import { formatDateTime } from "@/lib/date";

function bytes(value: number): string { if (value < 1024) return `${value} B`; if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`; return `${(value / (1024 * 1024)).toFixed(1)} MB`; }
function statusTone(status: string): StatusTone { if (status === "indexed") return "success"; if (status === "failed") return "destructive"; if (["deleting", "processing", "queued", "uploading"].includes(status)) return "pending"; if (status === "deleted") return "unavailable"; return "info"; }

export function DocumentAdministration({ workspacePublicId, initialPage }: Readonly<{ workspacePublicId: string; initialPage: DocumentPage }>) {
  const [documents, setDocuments] = useState<AdminDocument[]>(initialPage.data);
  const [pageMeta, setPageMeta] = useState(initialPage.meta);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("all");
  const [notice, setNotice] = useState<{ tone: "success" | "destructive"; message: string } | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const load = useCallback(async (requestedPage = 1) => { setLoading(true); try { const query = new URLSearchParams(); if (search) query.set("search", search); if (status !== "all") query.set("status", status); query.set("page", String(requestedPage)); query.set("per_page", String(pageMeta.per_page)); const page = await workspaceDocuments(workspacePublicId, query.toString()); setDocuments(page.data); setPageMeta(page.meta); setNotice(null); } catch (error) { setNotice({ tone: "destructive", message: firstError(error) }); } finally { setLoading(false); } }, [pageMeta.per_page, search, status, workspacePublicId]);
  async function submitFilters(event: FormEvent) { event.preventDefault(); await load(1); }
  async function retry(document: AdminDocument) { setBusy(document.public_id); try { await retryWorkspaceDocument(workspacePublicId, document.public_id, crypto.randomUUID()); setNotice({ tone: "success", message: "Retry accepted. The document is queued for ingestion." }); await load(); } catch (error) { setNotice({ tone: "destructive", message: firstError(error) }); } finally { setBusy(null); } }
  async function remove(document: AdminDocument) { setBusy(document.public_id); try { await deleteWorkspaceDocument(workspacePublicId, document.public_id); setNotice({ tone: "success", message: "Deletion accepted. Cleanup will continue asynchronously." }); await load(); } catch (error) { setNotice({ tone: "destructive", message: firstError(error) }); } finally { setBusy(null); } }

  return <section aria-labelledby="documents-heading" className="grid gap-5">
    <Card><CardHeader><CardTitle id="documents-heading">Document library</CardTitle><CardDescription>{pageMeta.total} sources in this workspace. Retry and delete controls appear only when the server authorises them.</CardDescription></CardHeader><CardContent><form className="grid gap-4 md:grid-cols-[minmax(14rem,1fr)_14rem_auto] md:items-end" onSubmit={submitFilters}><label className="grid gap-2 text-sm font-semibold" htmlFor="document-search">Search<Input id="document-search" onChange={(event) => setSearch(event.target.value)} placeholder="Filename" value={search} /></label><label className="grid gap-2 text-sm font-semibold">Status<Select onValueChange={setStatus} value={status}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{["uploading", "uploaded", "queued", "processing", "indexed", "failed", "deleting", "deleted"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label><Button disabled={loading} type="submit" variant="secondary">{loading ? "Filtering…" : "Apply filters"}</Button></form></CardContent></Card>
    {notice ? <Notice tone={notice.tone}>{notice.message}</Notice> : null}
    {!loading && documents.length === 0 ? <EmptyState description="Try changing the search or status filter." icon={FileSearch} title="No matching documents" /> : null}
    <div className="grid gap-4">{documents.map((document) => <Card key={document.public_id}><CardHeader className="gap-3 md:flex-row md:items-start md:justify-between"><div><CardTitle>{document.source_filename}</CardTitle><CardDescription>{document.media_type} · {bytes(document.size_bytes)}</CardDescription></div><StatusBadge status={statusTone(document.status)}>{document.status}</StatusBadge></CardHeader><CardContent className="grid gap-4"><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-foreground-muted">Governance</dt><dd className="mt-1 font-medium">{document.governance_status}</dd></div><div><dt className="text-foreground-muted">Added by</dt><dd className="mt-1 font-medium">{document.created_by?.name ?? "Unavailable"}</dd></div><div><dt className="text-foreground-muted">Created</dt><dd className="mt-1 font-medium">{formatDateTime(document.created_at)}</dd></div></dl>{document.failure_message ? <Notice tone="destructive"><strong>{document.failure_category}</strong><p>{document.failure_message}</p></Notice> : null}{document.deletion?.stuck ? <Notice tone="warning"><strong>Deletion needs attention</strong><p>{document.deletion.failure_code ?? "Cleanup has not completed."}</p></Notice> : null}{document.extraction_warnings.length > 0 ? <details className="rounded-lg border border-border p-4"><summary className="cursor-pointer font-semibold">{document.extraction_warnings.length} extraction warning(s)</summary><ul className="mt-3 grid gap-2 text-sm text-foreground-muted">{document.extraction_warnings.map((warning) => <li key={`${warning.code}-${warning.message}`}><strong className="text-foreground">{warning.code}</strong>: {warning.message}</li>)}</ul></details> : null}<div className="flex flex-wrap gap-2">{document.capabilities.retry ? <Button className="h-10 min-h-10" disabled={busy === document.public_id} onClick={() => void retry(document)} size="sm" type="button" variant="secondary"><RefreshCw />{busy === document.public_id ? "Working…" : "Retry ingestion"}</Button> : null}{document.capabilities.delete ? <AlertDialog><AlertDialogTrigger asChild><Button className="h-10 min-h-10" disabled={busy === document.public_id} size="sm" variant="destructive"><Trash2 />Delete</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>Delete {document.source_filename}?</AlertDialogTitle><AlertDialogDescription>The source will be removed from the knowledge base asynchronously. Passages already cited in completed conversations remain preserved with those conversations.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => void remove(document)}>Delete document</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog> : null}</div></CardContent></Card>)}</div>
    {pageMeta.last_page > 1 ? <nav aria-label="Document pages" className="flex items-center justify-between gap-4"><Button disabled={loading || pageMeta.current_page <= 1} onClick={() => void load(pageMeta.current_page - 1)} variant="outline">Previous</Button><span className="text-sm text-foreground-muted">Page {pageMeta.current_page} of {pageMeta.last_page}</span><Button disabled={loading || pageMeta.current_page >= pageMeta.last_page} onClick={() => void load(pageMeta.current_page + 1)} variant="outline">Next</Button></nav> : null}
  </section>;
}
