receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  probabilistic_sampler:
    sampling_percentage: ${env:OTEL_TRACE_SAMPLING_PERCENTAGE}
  batch:

exporters:
  otlp_http/local_backend:
    endpoint: ${env:OTEL_BACKEND_OTLP_ENDPOINT}
    compression: gzip
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - probabilistic_sampler
        - batch
      exporters:
        - otlp_http/local_backend
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_http/local_backend
